site_name: Linked Art
site_url: "https://linked.art/"
site_dir: ".site"
repo_url: "https://github.com/linked-art/linked.art"
site_author: "Rob Sanderson"
site_description: "Linked Open Usable Data for Cultural Heritage"
theme:
  name: material
  custom_dir: material/overrides
  palette:
    primary: custom
  logo: media/logo/linkedart-logo-horizontal.png
  favicon: media/logo/linkedart-favicon.png
  features:
    - navigation.tabs
    - navigation.path
    - header.autohide
  font: false
extra_css:
  - stylesheets/extra.css

copyright: © Linked Art Editorial Board. Published under the CC BY 4.0 license.

nav:
  - Home: "index.md"
  - Model: "model/index.md"
  - API: "api/1.0/index.md"
  - About: "about/index.md"
  - Community: "community/index.md"
  - Recipes: "cookbook/index.md"
  - Software: "software/index.md"

markdown_extensions:
  - fenced_code
  - def_list
  - tables
  - abbr
  - attr_list
  - admonition
  - toc:
      title: "Table of Contents"
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.blocks.admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:mermaid2.fence_mermaid # Custom vars to our template


extra:
  project:
    install: "https://github.com/linked-art/linked.art"
  build: production
  ga_tracking_code: XX-XXXXXXXX-X
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/linked-art/
    - icon: fontawesome/brands/slack
      link: https://linked-art.slack.com/

plugins:
  - search
  - mermaid2:
      javascript: "https://linked.art/media/vendor/mermaid.min.js"
      #version: '10.6.1'
      arguments:
        theme: "neutral"
        logLevel: 1
        flowchart:
          curve: "basis"
        securityLevel: "loose"
  - linkedart
