[build]
  # Base directory where site is built from
  base    = "."
  environment = { PYTHON_VERSION = "3.13" }
  # Directory published to
  publish = ".site"
  # command to run to build
  command = "sh ./build.sh"

